"""
Banco de dados de jogadores históricos para comparação
"""

LEGEND_DATABASE = [
    {
        "name": "Pelé",
        "nationality": "Brasil",
        "position": "Atacante",
        "height": 173,
        "weight": 70,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 9,
            "resistencia": 8,
            "forca": 7,
            "agilidade": 10,
            "passe": 9,
            "drible": 10,
            "finalizacao": 10,
            "chute": 10,
            "jogo_aereo": 8,
            "visao_de_jogo": 10,
            "posicionamento": 10,
            "marcacao": 5,
            "interceptacao": 4,
            "disciplina_tatica": 7
        },
        "distinctive_traits": ["Finalização excepcional", "Drible único", "Visão de jogo", "Liderança"],
        "playing_style": "Atacante completo e criativo",
        "era": "1950-1970"
    },
    {
        "name": "Diego Maradona",
        "nationality": "Argentina",
        "position": "Meia-Atacante",
        "height": 165,
        "weight": 70,
        "body_type": "Mesomorfo",
        "dominant_foot": "Canhoto",
        "technical_profile": {
            "velocidade": 8,
            "resistencia": 7,
            "forca": 6,
            "agilidade": 10,
            "passe": 10,
            "drible": 10,
            "finalizacao": 9,
            "chute": 9,
            "jogo_aereo": 5,
            "visao_de_jogo": 10,
            "posicionamento": 9,
            "marcacao": 4,
            "interceptacao": 3,
            "disciplina_tatica": 6
        },
        "distinctive_traits": ["Drible excepcional", "Criatividade", "Liderança", "Chute de longa distância"],
        "playing_style": "Meia criativo e driblador",
        "era": "1980-1990"
    },
    {
        "name": "Zinedine Zidane",
        "nationality": "França",
        "position": "Meia",
        "height": 185,
        "weight": 80,
        "body_type": "Mesomorfo",
        "dominant_foot": "Ambidestro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 8,
            "forca": 8,
            "agilidade": 8,
            "passe": 10,
            "drible": 9,
            "finalizacao": 8,
            "chute": 9,
            "jogo_aereo": 7,
            "visao_de_jogo": 10,
            "posicionamento": 9,
            "marcacao": 6,
            "interceptacao": 5,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Controle de bola", "Visão de jogo", "Passe longo", "Elegância"],
        "playing_style": "Meia organizador e criativo",
        "era": "1990-2000"
    },
    {
        "name": "Ronaldo Fenômeno",
        "nationality": "Brasil",
        "position": "Atacante",
        "height": 183,
        "weight": 82,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 10,
            "resistencia": 8,
            "forca": 9,
            "agilidade": 10,
            "passe": 7,
            "drible": 10,
            "finalizacao": 10,
            "chute": 10,
            "jogo_aereo": 8,
            "visao_de_jogo": 8,
            "posicionamento": 10,
            "marcacao": 4,
            "interceptacao": 3,
            "disciplina_tatica": 7
        },
        "distinctive_traits": ["Velocidade explosiva", "Drible em velocidade", "Finalização", "Força física"],
        "playing_style": "Atacante explosivo e completo",
        "era": "1990-2000"
    },
    {
        "name": "Lionel Messi",
        "nationality": "Argentina",
        "position": "Atacante",
        "height": 170,
        "weight": 72,
        "body_type": "Ectomorfo",
        "dominant_foot": "Canhoto",
        "technical_profile": {
            "velocidade": 9,
            "resistencia": 9,
            "forca": 6,
            "agilidade": 10,
            "passe": 10,
            "drible": 10,
            "finalizacao": 10,
            "chute": 10,
            "jogo_aereo": 6,
            "visao_de_jogo": 10,
            "posicionamento": 10,
            "marcacao": 5,
            "interceptacao": 4,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Drible único", "Finalização precisa", "Visão de jogo", "Controle de bola"],
        "playing_style": "Atacante criativo e técnico",
        "era": "2000-2020"
    },
    {
        "name": "Cristiano Ronaldo",
        "nationality": "Portugal",
        "position": "Atacante",
        "height": 187,
        "weight": 83,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 9,
            "resistencia": 10,
            "forca": 9,
            "agilidade": 9,
            "passe": 8,
            "drible": 9,
            "finalizacao": 10,
            "chute": 10,
            "jogo_aereo": 10,
            "visao_de_jogo": 8,
            "posicionamento": 10,
            "marcacao": 5,
            "interceptacao": 4,
            "disciplina_tatica": 9
        },
        "distinctive_traits": ["Jogo aéreo excepcional", "Finalização", "Físico atlético", "Disciplina"],
        "playing_style": "Atacante completo e atlético",
        "era": "2000-2020"
    },
    {
        "name": "Franz Beckenbauer",
        "nationality": "Alemanha",
        "position": "Zagueiro",
        "height": 181,
        "weight": 75,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 8,
            "forca": 8,
            "agilidade": 7,
            "passe": 9,
            "drible": 7,
            "finalizacao": 6,
            "chute": 7,
            "jogo_aereo": 8,
            "visao_de_jogo": 10,
            "posicionamento": 10,
            "marcacao": 9,
            "interceptacao": 9,
            "disciplina_tatica": 10
        },
        "distinctive_traits": ["Leitura de jogo", "Técnica", "Liderança", "Versatilidade"],
        "playing_style": "Zagueiro técnico e organizador",
        "era": "1960-1980"
    },
    {
        "name": "Franco Baresi",
        "nationality": "Itália",
        "position": "Zagueiro",
        "height": 176,
        "weight": 70,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 8,
            "resistencia": 8,
            "forca": 7,
            "agilidade": 8,
            "passe": 8,
            "drible": 6,
            "finalizacao": 5,
            "chute": 6,
            "jogo_aereo": 7,
            "visao_de_jogo": 9,
            "posicionamento": 10,
            "marcacao": 10,
            "interceptacao": 10,
            "disciplina_tatica": 10
        },
        "distinctive_traits": ["Posicionamento", "Antecipação", "Leitura de jogo", "Liderança"],
        "playing_style": "Zagueiro rápido e inteligente",
        "era": "1980-1990"
    },
    {
        "name": "Alessandro Nesta",
        "nationality": "Itália",
        "position": "Zagueiro",
        "height": 187,
        "weight": 79,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 7,
            "forca": 8,
            "agilidade": 7,
            "passe": 8,
            "drible": 6,
            "finalizacao": 5,
            "chute": 6,
            "jogo_aereo": 9,
            "visao_de_jogo": 8,
            "posicionamento": 9,
            "marcacao": 9,
            "interceptacao": 9,
            "disciplina_tatica": 9
        },
        "distinctive_traits": ["Elegância", "Jogo aéreo", "Técnica", "Posicionamento"],
        "playing_style": "Zagueiro elegante e técnico",
        "era": "1990-2010"
    },
    {
        "name": "Lothar Matthäus",
        "nationality": "Alemanha",
        "position": "Volante",
        "height": 174,
        "weight": 70,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 9,
            "forca": 8,
            "agilidade": 7,
            "passe": 8,
            "drible": 7,
            "finalizacao": 7,
            "chute": 8,
            "jogo_aereo": 7,
            "visao_de_jogo": 8,
            "posicionamento": 8,
            "marcacao": 9,
            "interceptacao": 9,
            "disciplina_tatica": 9
        },
        "distinctive_traits": ["Combate físico", "Liderança", "Resistência", "Chute de longa distância"],
        "playing_style": "Volante combativo e completo",
        "era": "1980-2000"
    },
    {
        "name": "Frank Rijkaard",
        "nationality": "Holanda",
        "position": "Volante",
        "height": 190,
        "weight": 85,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 8,
            "forca": 9,
            "agilidade": 6,
            "passe": 8,
            "drible": 6,
            "finalizacao": 6,
            "chute": 7,
            "jogo_aereo": 8,
            "visao_de_jogo": 8,
            "posicionamento": 8,
            "marcacao": 9,
            "interceptacao": 9,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Físico", "Presença", "Versatilidade", "Liderança"],
        "playing_style": "Volante físico e versátil",
        "era": "1980-1990"
    },
    {
        "name": "Andrea Pirlo",
        "nationality": "Itália",
        "position": "Volante",
        "height": 177,
        "weight": 68,
        "body_type": "Ectomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 5,
            "resistencia": 7,
            "forca": 5,
            "agilidade": 6,
            "passe": 10,
            "drible": 7,
            "finalizacao": 6,
            "chute": 8,
            "jogo_aereo": 5,
            "visao_de_jogo": 10,
            "posicionamento": 9,
            "marcacao": 6,
            "interceptacao": 6,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Passe longo", "Visão de jogo", "Técnica", "Elegância"],
        "playing_style": "Volante organizador e técnico",
        "era": "2000-2010"
    },
    {
        "name": "Xavi Hernández",
        "nationality": "Espanha",
        "position": "Meia",
        "height": 170,
        "weight": 68,
        "body_type": "Ectomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 6,
            "resistencia": 9,
            "forca": 5,
            "agilidade": 7,
            "passe": 10,
            "drible": 8,
            "finalizacao": 6,
            "chute": 6,
            "jogo_aereo": 4,
            "visao_de_jogo": 10,
            "posicionamento": 9,
            "marcacao": 7,
            "interceptacao": 7,
            "disciplina_tatica": 9
        },
        "distinctive_traits": ["Passe curto", "Controle de jogo", "Resistência", "Técnica"],
        "playing_style": "Meia organizador e controlador",
        "era": "2000-2010"
    },
    {
        "name": "Andrés Iniesta",
        "nationality": "Espanha",
        "position": "Meia",
        "height": 171,
        "weight": 68,
        "body_type": "Ectomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 7,
            "resistencia": 9,
            "forca": 5,
            "agilidade": 9,
            "passe": 9,
            "drible": 10,
            "finalizacao": 7,
            "chute": 7,
            "jogo_aereo": 4,
            "visao_de_jogo": 9,
            "posicionamento": 8,
            "marcacao": 6,
            "interceptacao": 5,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Drible", "Controle de bola", "Criatividade", "Resistência"],
        "playing_style": "Meia criativo e driblador",
        "era": "2000-2010"
    },
    {
        "name": "Romário",
        "nationality": "Brasil",
        "position": "Atacante",
        "height": 169,
        "weight": 72,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 8,
            "resistencia": 7,
            "forca": 6,
            "agilidade": 10,
            "passe": 7,
            "drible": 9,
            "finalizacao": 10,
            "chute": 9,
            "jogo_aereo": 6,
            "visao_de_jogo": 8,
            "posicionamento": 10,
            "marcacao": 4,
            "interceptacao": 3,
            "disciplina_tatica": 6
        },
        "distinctive_traits": ["Finalização", "Agilidade", "Posicionamento", "Drible em área"],
        "playing_style": "Atacante ágil e finalizador",
        "era": "1990-2000"
    },
    {
        "name": "Marco van Basten",
        "nationality": "Holanda",
        "position": "Atacante",
        "height": 188,
        "weight": 80,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 8,
            "resistencia": 7,
            "forca": 8,
            "agilidade": 8,
            "passe": 7,
            "drible": 8,
            "finalizacao": 10,
            "chute": 10,
            "jogo_aereo": 10,
            "visao_de_jogo": 8,
            "posicionamento": 10,
            "marcacao": 4,
            "interceptacao": 3,
            "disciplina_tatica": 7
        },
        "distinctive_traits": ["Finalização", "Jogo aéreo", "Técnica", "Completude"],
        "playing_style": "Atacante completo e técnico",
        "era": "1980-1990"
    },
    {
        "name": "Manuel Neuer",
        "nationality": "Alemanha",
        "position": "Goleiro",
        "height": 193,
        "weight": 92,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 6,
            "resistencia": 7,
            "forca": 8,
            "agilidade": 7,
            "passe": 8,
            "drible": 5,
            "finalizacao": 3,
            "chute": 4,
            "jogo_aereo": 9,
            "visao_de_jogo": 9,
            "posicionamento": 10,
            "marcacao": 3,
            "interceptacao": 8,
            "reflexos": 9,
            "jogo_com_os_pes": 10,
            "disciplina_tatica": 9
        },
        "distinctive_traits": ["Jogo com os pés", "Posicionamento", "Saída de gol", "Liderança"],
        "playing_style": "Goleiro moderno e técnico",
        "era": "2010-2020"
    },
    {
        "name": "Philipp Lahm",
        "nationality": "Alemanha",
        "position": "Lateral",
        "height": 170,
        "weight": 66,
        "body_type": "Ectomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 8,
            "resistencia": 9,
            "forca": 6,
            "agilidade": 8,
            "passe": 9,
            "drible": 7,
            "finalizacao": 6,
            "chute": 7,
            "jogo_aereo": 6,
            "visao_de_jogo": 9,
            "posicionamento": 9,
            "marcacao": 8,
            "interceptacao": 8,
            "disciplina_tatica": 10
        },
        "distinctive_traits": ["Disciplina tática", "Versatilidade", "Inteligência", "Liderança"],
        "playing_style": "Lateral inteligente e disciplinado",
        "era": "2000-2010"
    },
    {
        "name": "Cafu",
        "nationality": "Brasil",
        "position": "Lateral",
        "height": 176,
        "weight": 75,
        "body_type": "Mesomorfo",
        "dominant_foot": "Destro",
        "technical_profile": {
            "velocidade": 9,
            "resistencia": 10,
            "forca": 7,
            "agilidade": 8,
            "passe": 8,
            "drible": 7,
            "finalizacao": 6,
            "chute": 7,
            "jogo_aereo": 7,
            "visao_de_jogo": 8,
            "posicionamento": 8,
            "marcacao": 8,
            "interceptacao": 7,
            "disciplina_tatica": 8
        },
        "distinctive_traits": ["Resistência", "Velocidade", "Ataque", "Liderança"],
        "playing_style": "Lateral ofensivo e resistente",
        "era": "1990-2000"
    }
]

# Templates de posições com características ideais
POSITION_TEMPLATES = {
    "Goleiro": {
        "ideal_height": (185, 195),
        "key_skills": ["reflexos", "posicionamento", "jogo_com_os_pes", "jogo_aereo"],
        "preferred_body_types": ["Mesomorfo", "Longilíneo"]
    },
    "Zagueiro": {
        "ideal_height": (175, 190),
        "key_skills": ["marcacao", "interceptacao", "posicionamento", "jogo_aereo", "visao_de_jogo"],
        "preferred_body_types": ["Mesomorfo"]
    },
    "Lateral": {
        "ideal_height": (170, 180),
        "key_skills": ["velocidade", "resistencia", "marcacao", "passe", "disciplina_tatica"],
        "preferred_body_types": ["Mesomorfo", "Ectomorfo"]
    },
    "Volante": {
        "ideal_height": (170, 185),
        "key_skills": ["marcacao", "interceptacao", "passe", "visao_de_jogo", "disciplina_tatica"],
        "preferred_body_types": ["Mesomorfo"]
    },
    "Meia": {
        "ideal_height": (165, 180),
        "key_skills": ["passe", "drible", "visao_de_jogo", "posicionamento", "criatividade"],
        "preferred_body_types": ["Ectomorfo", "Mesomorfo"]
    },
    "Atacante": {
        "ideal_height": (170, 190),
        "key_skills": ["finalizacao", "velocidade", "drible", "posicionamento", "jogo_aereo"],
        "preferred_body_types": ["Mesomorfo", "Ectomorfo"]
    }
}

